# Jenkins Slave Setup Playbook
# This playbook provisions a Jenkins build agent with Java, Maven, Docker, and Docker Buildx.
# It ensures the Jenkins agent user (e.g., 'ubuntu') has Docker access and reboots the system if needed.

---
- hosts: jenkins-slave
  become: yes
  tasks:

    # Update the apt package index to ensure latest package info
    - name: Update Ubuntu repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    # Install Java 21 and fontconfig (required for Maven and Jenkins)
    - name: Install OpenJDK 21 JDK and fontconfig
      apt:
        name:
          - fontconfig
          - openjdk-21-jdk
        state: present

    # Download Maven 3.9.9 binary
    - name: Download Maven packages
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        dest: /opt/apache-maven-3.9.9-bin.tar.gz

    # Extract Maven to /opt
    - name: Extract Maven packages
      unarchive:
        src: /opt/apache-maven-3.9.9-bin.tar.gz
        dest: /opt/
        remote_src: yes

    # Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    # Start Docker service immediately
    - name: Start Docker service
      service:
        name: docker
        state: started

    # Refresh system facts to ensure Docker group is recognized
    - name: Refresh facts after Docker install
      setup:

    # Ensure Jenkins user exists (optional, for flexibility)
    - name: Ensure jenkins user exists
      user:
        name: jenkins
        state: present

    # Add Jenkins user to docker group (if used)
    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes
      register: jenkins_docker_group

    # Reboot if Jenkins user group membership changed
    - name: Reboot if Jenkins group membership changed
      reboot:
        msg: "Reboot to apply docker group membership for Jenkins user"
        pre_reboot_delay: 5
        post_reboot_delay: 30
        reboot_timeout: 600
      when: jenkins_docker_group.changed

    # Restart Jenkins service if it exists (optional)
    - name: Restart Jenkins agent service
      service:
        name: jenkins
        state: restarted
      when: ansible_facts.services['jenkins.service'] is defined

    # Install Docker Buildx plugin for advanced Docker builds
    - name: Install Docker Buildx plugin system-wide
      shell: |
        set -e
        mkdir -p /usr/libexec/docker/cli-plugins
        BUILDX_URL="https://github.com/docker/buildx/releases/download/v0.13.1/buildx-v0.13.1.linux-amd64"
        curl -sSL $BUILDX_URL -o /usr/libexec/docker/cli-plugins/docker-buildx
        chmod +x /usr/libexec/docker/cli-plugins/docker-buildx
      args:
        executable: /bin/bash
      register: buildx_install
      changed_when: buildx_install.rc == 0

    # Verify Docker Buildx installation
    - name: Verify Docker Buildx installation
      command: docker buildx version
      register: buildx_version
      changed_when: false
      failed_when: buildx_version.rc != 0

    # Enable Docker BuildKit for better performance and caching
    - name: Enable Docker BuildKit
      lineinfile:
        path: /etc/environment
        line: DOCKER_BUILDKIT=1
        create: yes
      notify: Restart Docker

    # Enable Docker to start on boot
    - name: Enable Docker on boot
      service:
        name: docker
        enabled: yes

    # ✅ NEW: Add ubuntu user to docker group (unconditionally)
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      register: ubuntu_docker_group

    # ✅ NEW: Reboot if ubuntu user group membership changed
    - name: Reboot if ubuntu group membership changed
      reboot:
        msg: "Reboot to apply docker group membership for ubuntu user"
        pre_reboot_delay: 5
        post_reboot_delay: 30
        reboot_timeout: 600
      when: ubuntu_docker_group.changed

    # Install kubectl (Kubernetes CLI) for managing EKS clusters
    - name: Download kubectl binary
      get_url:
        url: https://dl.k8s.io/release/v1.30.1/bin/linux/amd64/kubectl  # Download the latest stable kubectl
        dest: /tmp/kubectl
        mode: '0755'

    - name: Make kubectl executable
      file:
        path: /tmp/kubectl
        mode: '0755'  # Ensure the binary is executable
        state: file

    - name: Move kubectl to /usr/local/bin
      command: mv /tmp/kubectl /usr/local/bin/kubectl  # Place kubectl in system PATH
      args:
        creates: /usr/local/bin/kubectl
      become: yes

    - name: Ensure kubectl is in PATH and executable
      command: kubectl version --client  # Verify kubectl installation
      register: kubectl_version
      changed_when: false
      failed_when: kubectl_version.rc != 0

    # Download AWS CLI v2 installer (zip archive)
    - name: Download AWS CLI v2 installer
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip  # Download the latest AWS CLI v2
        dest: /tmp/awscliv2.zip
        mode: '0644'

    # Ensure unzip is installed (required to extract AWS CLI installer)
    - name: Install unzip (required for AWS CLI installer)
      apt:
        name: unzip
        state: present

    # Extract AWS CLI installer from the downloaded zip file
    - name: Unzip AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes

    # Run the AWS CLI installer script to install or update AWS CLI v2
    - name: Install or update AWS CLI v2
      shell: |
        /tmp/aws/install --update  # Install or update AWS CLI to the latest version
      args:
        creates: /usr/local/bin/aws
      become: yes

    # Verify AWS CLI installation and version
    - name: Verify AWS CLI installation
      command: aws --version  # Confirm AWS CLI is installed and in PATH
      register: awscli_version
      changed_when: false
      failed_when: awscli_version.rc != 0

    # Install Helm (Kubernetes package manager)
    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Run Helm install script
      shell: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm
      become: yes

    - name: Verify Helm installation
      command: helm version --short
      register: helm_version
      changed_when: false
      failed_when: helm_version.rc != 0

    # Add stable Helm repository and update repo cache
    - name: Add stable Helm repository
      command: helm repo add stable https://charts.helm.sh/stable
      register: helm_repo_add
      changed_when: helm_repo_add.rc == 0
      failed_when: helm_repo_add.rc != 0

    - name: Update Helm repositories
      command: helm repo update
      register: helm_repo_update
      changed_when: helm_repo_update.rc == 0
      failed_when: helm_repo_update.rc != 0

    # Add Bitnami Helm repository for MySQL
    - name: Add Bitnami Helm repository
      command: helm repo add bitnami https://charts.bitnami.com/bitnami
      register: helm_repo_add_bitnami
      changed_when: helm_repo_add_bitnami.rc == 0
      failed_when: helm_repo_add_bitnami.rc != 0

    - name: Update Helm repositories (after adding Bitnami)
      command: helm repo update
      register: helm_repo_update_bitnami
      changed_when: helm_repo_update_bitnami.rc == 0
      failed_when: helm_repo_update_bitnami.rc != 0

    # Install MySQL using Bitnami Helm chart
    - name: Install MySQL using Bitnami Helm chart
      command: helm install demo-mysql bitnami/mysql --namespace automationsaan --create-namespace --set auth.rootPassword=changeme --set primary.persistence.enabled=false
      register: helm_mysql_install
      changed_when: helm_mysql_install.rc == 0
      failed_when: helm_mysql_install.rc != 0

    # Pull the MySQL Helm chart package to local
    - name: Pull bitnami/mysql Helm chart package to local
      command: helm pull bitnami/mysql
      register: helm_mysql_pull
      changed_when: helm_mysql_pull.rc == 0
      failed_when: helm_mysql_pull.rc != 0

    # Add Prometheus Community Helm repository (contains kube-prometheus-stack for Prometheus + Grafana)
    - name: Add Prometheus Community Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      register: helm_repo_add_prometheus
      changed_when: helm_repo_add_prometheus.rc == 0
      failed_when: helm_repo_add_prometheus.rc != 0

    # Update Helm repositories to fetch latest charts, including kube-prometheus-stack
    - name: Update Helm repositories (after adding Prometheus)
      command: helm repo update
      register: helm_repo_update_prometheus
      changed_when: helm_repo_update_prometheus.rc == 0
      failed_when: helm_repo_update_prometheus.rc != 0

    # Install kube-prometheus-stack (Prometheus + Grafana + exporters) using Helm
    # This chart deploys a full monitoring stack: Prometheus, Grafana, Alertmanager, node-exporter, and more
    # The namespace 'automationsaan-prom-monitoring' will be created if it does not exist
    # The --set prometheus.prometheusSpec.maximumStartupDurationSeconds=300 flag is required to avoid CRD validation errors (must be >= 60)
    # The following flags expose both Prometheus and Grafana via AWS LoadBalancer services
    - name: Install kube-prometheus-stack (Prometheus + Grafana) using Helm chart
      command: >
        helm install prometheus prometheus-community/kube-prometheus-stack
        --namespace automationsaan-prom-monitoring
        --create-namespace
        --set prometheus.prometheusSpec.maximumStartupDurationSeconds=300
        --set prometheus.service.type=LoadBalancer
        --set grafana.service.type=LoadBalancer
      register: helm_kube_prom_stack_install
      changed_when: helm_kube_prom_stack_install.rc == 0
      failed_when: helm_kube_prom_stack_install.rc != 0

    # Optionally pull the kube-prometheus-stack Helm chart package to local for inspection/offline use
    # The chart archive will be saved to /home/ubuntu for easy access
    - name: Pull prometheus-community/kube-prometheus-stack Helm chart package to /home/ubuntu
      command: helm pull prometheus-community/kube-prometheus-stack --destination /home/ubuntu
      register: helm_kube_prom_stack_pull
      changed_when: helm_kube_prom_stack_pull.rc == 0
      failed_when: helm_kube_prom_stack_pull.rc != 0

    # Unpack the kube-prometheus-stack Helm chart archive in /home/ubuntu for inspection
    - name: Extract kube-prometheus-stack Helm chart package in /home/ubuntu
      unarchive:
        src: /home/ubuntu/kube-prometheus-stack-72.6.3.tgz
        dest: /home/ubuntu/
        remote_src: yes
      register: helm_kube_prom_stack_unarchive
      changed_when: helm_kube_prom_stack_unarchive.changed
      failed_when: helm_kube_prom_stack_unarchive.failed

    # (Optional) Commented out: Remove previous Prometheus-only install if present
    # - name: Uninstall old Prometheus-only Helm release (if exists)
    #   command: helm uninstall demo-prometheus -n automationsaan-prom-monitoring
    #   ignore_errors: yes
    #   changed_when: false
    #   failed_when: false
  handlers:
    # Restart Docker if BuildKit or config changes
    - name: Restart Docker
      service:
        name: docker
        state: restarted

# NOTES: Accessing Grafana and Prometheus after Service Type Change
# ----------------------------------------------------------------
# After running this playbook, both Grafana and Prometheus will be exposed via AWS LoadBalancer services.
# To access them:
#
# 1. Get the external DNS/hostname for each service:
#    kubectl get svc -n automationsaan-prom-monitoring
#
#    Example output:
#    NAME                TYPE           CLUSTER-IP      EXTERNAL-IP                                                               PORT(S)   AGE
#    prometheus-grafana  LoadBalancer   172.20.45.167   a766a756a42b943ac99dfb375972f2a1-1304622396.us-west-2.elb.amazonaws.com   80:...   ...
#    prometheus-...      LoadBalancer   ...             ...                                                                       9090:...  ...
#
# 2. Access Grafana:
#    http://<EXTERNAL-IP-or-DNS>:80
#    (Default credentials: admin/prom-operator unless overridden)
#
# 3. Access Prometheus:
#    http://<EXTERNAL-IP-or-DNS>:9090
#
# 4. If you do not see an EXTERNAL-IP immediately, wait a few minutes for AWS to provision the ELB.
#
# 5. For security, restrict access to these LoadBalancers using AWS security groups as needed.
