---
- name: Install Jenkins and OpenJDK 21 on Ubuntu 22.04+
  hosts: all
  become: yes

  tasks:
    - name: Ensure keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins apt repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        filename: jenkins
        state: present

    - name: Add Adoptium (Temurin) PPA for OpenJDK 21
      apt_repository:
        repo: "ppa:adoptium/ppa"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 21 (Temurin)
      apt:
        name: temurin-21-jdk
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins is started and enabled
      systemd:
        name: jenkins
        enabled: yes
        state: started
