---
- name: Install Java and Jenkins on Ubuntu 22.04
  hosts: jenkins-master
  become: yes

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install OpenJDK 17 (Java)
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Update apt cache after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins is started and enabled
      systemd:
        name: jenkins
        enabled: yes
        state: started
