---
- hosts: jenkins-slave
  become: yes 
  tasks: 
  - name: update ubuntu repo and cache 
    apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600 

  - name: Install OpenJDK 21 and fontconfig
    apt:
      name:
        - fontconfig
        - openjdk-21-jre
      state: present

# Set JAVA_HOME environment variable
  - name: Set JAVA_HOME environment variable system-wide
    copy:
      dest: /etc/profile.d/java_home.sh
      content: |
        export JAVA_HOME=/lib/jvm/java-21-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
      mode: '0755'

  - name: download maven packages 
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      dest: /opt

  - name: extract maven packages 
    unarchive:
      src: /opt/apache-maven-3.9.9-bin.tar.gz
      dest: /opt 
      remote_src: yes

  - name: Set MAVEN_HOME environment variable system-wide
    copy:
      dest: /etc/profile.d/maven_home.sh
      content: |
        export MAVEN_HOME=/opt/apache-maven-3.9.9
        export PATH=$MAVEN_HOME/bin:$PATH
      mode: '0755'

  - name: install docker 
    apt: 
      name: docker.io 
      state: present

  - name: start docker services 
    service: 
      name: docker 
      state: started 
  
  - name: give 777 permissions on /var/run/docker.sock
    file: 
      path: /var/run/docker.sock
      state: file 
      mode: 0777

  - name: start docker on boot time 
    service: 
      name: docker 
      enabled: yes 